language: node_js
node_js:
  - 16
cache:
  directories:
  - node_modules
script:
  - npm install && npm run build -ws
  - npm run test:ci
after_failure: cat /home/travis/.npm/_logs/*-debug.log
warnings_are_errors: false
env:
  CI=false